#!/bin/bash
# Script to help set up GitHub Secrets
# Run this locally to see what secrets need to be configured

echo "🔐 GitHub Secrets Configuration Guide"
echo "======================================"
echo ""
echo "Navigate to: Settings → Secrets and variables → Actions → New repository secret"
echo ""
echo "Required Secrets:"
echo ""
echo "1. SSH_PRIVATE_KEY"
echo "   Description: Private SSH key for server access"
echo "   Generate with: ssh-keygen -t ed25519 -C 'github-actions'"
echo "   Add public key to server: ~/.ssh/authorized_keys"
echo ""
echo "2. SSH_USER"
echo "   Description: SSH username for server access"
echo "   Example: frappe, ubuntu, root"
echo ""
echo "3. SERVER_HOST"
echo "   Description: Server hostname or IP address"
echo "   Example: production.example.com, 192.168.1.100"
echo ""
echo "4. BENCH_DIRECTORY"
echo "   Description: Path to bench directory on server"
echo "   Example: /home/frappe/frappe-bench"
echo ""
echo "5. SONAR_TOKEN (Optional)"
echo "   Description: SonarQube authentication token"
echo "   Get from: SonarQube → My Account → Security"
echo ""
echo "6. SONAR_HOST_URL (Optional)"
echo "   Description: SonarQube server URL"
echo "   Example: https://sonarcloud.io"
echo ""
echo "7. SLACK_WEBHOOK_URL (Optional)"
echo "   Description: Slack webhook URL for notifications"
echo "   Create at: https://api.slack.com/messaging/webhooks"
echo ""
echo "8. DISCORD_WEBHOOK_URL (Optional)"
echo "   Description: Discord webhook URL for notifications"
echo "   Create at: Server Settings → Integrations → Webhooks"
echo ""
echo "9. BENCH_PATH (Optional)"
echo "   Description: Path to bench executable (for tests)"
echo "   Example: /home/frappe/frappe-bench"
echo ""

